#spring.application.name=Identity
spring:
  application:
    name: Identity
  datasource:
    url: jdbc:mysql://localhost:3306/identity_db?useSSL=false&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080