#spring.application.name=Identity
spring:
  application:
    name: Identity
  datasource:
    url: jdbc:mysql://localhost:3306/aone?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: nerosoft.8888
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080
  error:
    include-message: always
    include-stacktrace: on_param